upstream backend_app {
    server backend:9000;
}

server {
    listen 80 default_server;
    server_name localhost reverse-proxy.lab;

    server_tokens off;
    client_max_body_size 1m;
    client_header_timeout 10s;
    client_body_timeout 10s;
    send_timeout 30s;

    include /etc/nginx/includes/lab_locations.conf;
}

server {
    listen 443 ssl;
    server_name localhost reverse-proxy.lab;

    ssl_certificate /etc/nginx/certs/student-server.crt;
    ssl_certificate_key /etc/nginx/certs/student-server.key;

    server_tokens off;
    client_max_body_size 1m;
    client_header_timeout 10s;
    client_body_timeout 10s;
    send_timeout 30s;

    include /etc/nginx/includes/lab_locations.conf;
}

# TODO 1:
# Dodaj upstream o nazwie backend_app, ktory wskazuje na backend:9000.

# TODO 2:
# Dodaj blok HTTPS server na porcie 443.
# Powinien uzywac:
#   ssl_certificate /etc/nginx/certs/student-server.crt;
#   ssl_certificate_key /etc/nginx/certs/student-server.key;
# W bloku HTTPS tez dolacz /etc/nginx/includes/lab_locations.conf.
